import test from 'node:test';
import assert from 'node:assert/strict';
import { GameEngine } from '../src/game/engine/GameEngine';
import { attackToughness, sourceAbilities, unitKeywords } from '../src/game/attachments/queries';
import { allocationGroups, allocationModel } from '../src/game/attachments/AllocationGroups';
import { effectiveCharacteristic } from '../src/game/effects/EffectEngine';
import { processAttachmentCasualties, finishAttacker } from '../src/game/attachments/AttachmentController';
import { field, embarked, ok, no } from './transports.helpers';
function shooting() { const s=field();s.phase='Shooting';s.turn=2;s.activePlayerId='player-2';return s; }
function successfulDamage() {let i=0;return()=>[.99,.99,0][i++%3]!;}
test('highest bodyguard toughness overrides weaker bodyguard and both Characters',()=>{const s=field(),u=s.units.find(u=>u.id==='attached')!;u.models[0]!.toughness=6;assert.equal(attackToughness(s,u),6);new GameEngine(s);});
test('normal Shooting protects Characters while any Bodyguard remains',()=>{const e=new GameEngine(shooting());ok(e.beginShooting('enemy'));const r=ok(e.fireWeapon('test-carbine','attached',successfulDamage()));assert.equal(r.woundTarget,3);assert.equal(r.destroyedModelIds.length,5);assert.ok(r.destroyedModelIds.every(id=>id.startsWith('bodyguard:')));assert.ok(e.getState().attachments![0]!.active);new GameEngine(e.getState());ok(e.completeShooting());assert.equal(e.getState().attachments![0]!.active,false);new GameEngine(e.getState());});
test('Precision optionally selects visible Character instead of Bodyguard',()=>{const e=new GameEngine(shooting());ok(e.beginShooting('enemy'));assert.ok(e.precisionTargets('enemy','test-carbine','attached').includes('leader:model:1'));const r=ok(e.fireWeapon('test-carbine','attached',successfulDamage(),'leader:model:1'));assert.equal(r.damageResults[0]!.modelId,'leader:model:1');assert.ok(r.destroyedModelIds.includes('leader:model:1'));assert.ok(e.getState().units.find(u=>u.id==='attached')!.models.some(m=>m.componentUnitId==='bodyguard'&&m.alive));new GameEngine(e.getState());});
test('invisible Character cannot be selected for Precision; no RNG consumed',()=>{const e=new GameEngine(shooting(),{visibility:(_a,b)=>!b.id.startsWith('leader:')});ok(e.beginShooting('enemy'));const before=e.getState();let rolls=0;no(e.fireWeapon('test-carbine','attached',()=>{rolls++;return .9;},'leader:model:1'),'PRECISION_TARGET_INVALID');assert.equal(rolls,0);assert.deepEqual(e.getState(),before);});
test('non-Precision weapon cannot target Character group',()=>{const s=shooting();s.definitions=s.definitions.map(d=>({...d,weapons:d.weapons.map(w=>({...w,traits:[]}))}));const e=new GameEngine(s);ok(e.beginShooting('enemy'));no(e.fireWeapon('test-carbine','attached',()=>.9,'leader:model:1'),'PRECISION_TARGET_INVALID');});
test('ordinary allocation selects wounded noncharacter before wounded character',()=>{const s=field(),u=s.units.find(u=>u.id==='attached')!;s.definitions=s.definitions.map(d=>d.id==='test-bodyguard'?{...d,stats:{...d.stats,wounds:2}}:d);u.models.filter(m=>m.componentUnitId==='bodyguard').forEach(m=>m.woundsRemaining=2);u.models[2]!.woundsRemaining=1;u.models[5]!.woundsRemaining=1;assert.equal(allocationModel(s,u)!.id,u.models[2]!.id);assert.equal(allocationGroups(s,u)[0]!.character,false);});
test('wounded Character precedes unwounded Character after Bodyguard dies',()=>{const s=field(),u=s.units.find(u=>u.id==='attached')!;u.models.filter(m=>m.componentUnitId==='bodyguard').forEach(m=>{m.alive=false;m.woundsRemaining=0;});u.models[6]!.woundsRemaining=1;assert.equal(allocationModel(s,u)!.componentUnitId,'support');});
test('Bodyguard and Leader unit abilities combine but a model ability stays on its source',()=>{const s=field(),u=s.units.find(u=>u.id==='attached')!;s.definitions=s.definitions.map(d=>d.id==='test-bodyguard'?{...d,abilities:[{id:'body-bonus',name:'Test',parameters:{},scope:'UNIT',effect:{kind:'MODIFIER',characteristic:'MOVE',value:1}}]}:d);u.models[0]!.abilities=[{id:'personal',name:'Test',parameters:{},effect:{kind:'MODIFIER',characteristic:'MOVE',value:2}}];assert.equal(effectiveCharacteristic(s,u.id,'MOVE',7,u.models[0]!.id),10);assert.equal(effectiveCharacteristic(s,u.id,'MOVE',7,u.models[1]!.id),8);assert.equal(effectiveCharacteristic(s,u.id,'LEADERSHIP',7),6);});
test('split retains wounds, shock, shooting history, movement state and own keywords',()=>{const s=field(),u=s.units.find(u=>u.id==='attached')!;u.state.battleShocked=true;u.state.hasMoved=true;u.lastRangedAttackTurnIndex=1;u.models[5]!.woundsRemaining=2;u.models.filter(m=>m.componentUnitId==='bodyguard').forEach(m=>{m.alive=false;m.woundsRemaining=0;});processAttachmentCasualties(s,'enemy');finishAttacker(s,'enemy');const leader=s.units.find(u=>u.id==='leader')!,support=s.units.find(u=>u.id==='support')!;assert.equal(leader.models[0]!.woundsRemaining,2);assert.equal(leader.state.battleShocked,true);assert.equal(leader.state.hasMoved,true);assert.equal(leader.lastRangedAttackTurnIndex,1);assert.ok(!unitKeywords(s,support).includes('PSYKER'));new GameEngine(s);});
test('split while embarked preserves valid living parents and removes dead component parent',()=>{const s=embarked(),u=s.units.find(u=>u.id==='attached')!;u.models.filter(m=>m.componentUnitId==='bodyguard').forEach(m=>{m.alive=false;m.woundsRemaining=0;});processAttachmentCasualties(s);assert.equal(s.units.find(u=>u.id==='leader')!.embarked!.transportId,'transport-b');assert.equal(s.units.find(u=>u.id==='bodyguard')!.embarked,undefined);new GameEngine(s);});
test('component destruction event contains only its original keywords',()=>{const s=field(),u=s.units.find(u=>u.id==='attached')!;u.models.filter(m=>m.componentUnitId==='bodyguard').forEach(m=>{m.alive=false;m.woundsRemaining=0;});processAttachmentCasualties(s,'enemy');const event=s.events.find(e=>e.type==='flow'&&e.name==='ATTACHED_COMPONENT_DESTROYED');assert.ok(event?.type==='flow');assert.deepEqual(event.detail.keywords,['INFANTRY']);});
test('passenger abilities do not transfer without explicit Firing Deck permission',()=>{const s=embarked();s.phase='Shooting';s.definitions=s.definitions.map(d=>d.id==='test-leader'?{...d,abilities:[{id:'deck-bonus',name:'Test',parameters:{},scope:'UNIT',whileEmbarked:true,effect:{kind:'MODIFIER',characteristic:'BS',value:-1}}]}:d);const e=new GameEngine(s);ok(e.beginShooting('transport-b',[{modelId:'leader:model:1',weaponId:'test-rifle'}]));assert.equal(effectiveCharacteristic(e.getState(),'transport-b','BS',3),3);});
test('explicit while-embarked via-Deck modifier applies only during loadout',()=>{const s=embarked();s.phase='Shooting';s.definitions=s.definitions.map(d=>d.id==='test-leader'?{...d,abilities:[{id:'deck-bonus',name:'Test',parameters:{},scope:'UNIT',whileEmbarked:true,viaFiringDeck:true,effect:{kind:'MODIFIER',characteristic:'BS',value:-1}}]}:d);const e=new GameEngine(s);ok(e.beginShooting('transport-b',[{modelId:'leader:model:1',weaponId:'test-rifle'}]));assert.equal(effectiveCharacteristic(e.getState(),'transport-b','BS',3),2);ok(e.completeShooting());assert.equal(effectiveCharacteristic(e.getState(),'transport-b','BS',3),3);});
test('split preserves active temporary effects on living components and resumes snapshot',()=>{const e=new GameEngine(field());ok(e.enableMatchFlow());let s=e.getState();s.flow!.effects.push({id:`effect-${s.flow!.nextEffectId++}`,source:'test',target:{unitId:'attached'},payload:{kind:'MODIFIER',characteristic:'SAVE',value:-1},createdAt:{round:1,turn:1,phaseIndex:s.flow!.phaseIndex,playerId:'player-1',phase:'Movement'},expiry:'END_OF_CURRENT_TURN',expiryPlayerId:'player-1',stacking:'STACK',active:true});const u=s.units.find(u=>u.id==='attached')!;u.models.filter(m=>m.componentUnitId==='bodyguard').forEach(m=>{m.alive=false;m.woundsRemaining=0;});processAttachmentCasualties(s);assert.equal(s.flow!.effects.filter(e=>e.active).length,2);assert.equal(effectiveCharacteristic(s,'leader','SAVE',4),3);new GameEngine(s);});
test('last Characters destroyed restores Bodyguard identity and starting strength',()=>{const s=field(),u=s.units.find(u=>u.id==='attached')!;u.models.filter(m=>m.componentUnitId!=='bodyguard').forEach(m=>{m.alive=false;m.woundsRemaining=0;});processAttachmentCasualties(s);const body=s.units.find(u=>u.id==='bodyguard')!;assert.equal(body.definitionId,'test-bodyguard');assert.equal(body.models.length,5);assert.ok(!unitKeywords(s,body).includes('CHARACTER'));new GameEngine(s);});
