import test from 'node:test';
import assert from 'node:assert/strict';
import { GameEngine } from '../src/game/engine/GameEngine';
import { createUnit } from '../src/game/engine/createUnit';
import { AELDARI_DATASHEETS, EMPERORS_CHILDREN_DATASHEETS } from '../src/game/content/factionDatasheets';
import { AELDARI_PRESET, EMPERORS_CHILDREN_PRESET, createAeldariVsEmperorsChildrenMatch } from '../src/game/content/presets';
import { VERIFIED_MUSTER_ENTRIES } from '../src/game/content/verifiedEntries';
import { createAttackJob, runAttackJob } from '../src/game/combat/AttackPipeline';
import { createTestMatch } from '../src/game/data/prototype';
import { factionAttackWeapon } from '../src/game/content/attackAbilities';
import { expireEffects } from '../src/game/effects/EffectEngine';

test('exactly nineteen sourced datasheets have selectable equipment and matching fixed prices', () => {
  const catalog = [...AELDARI_DATASHEETS,...EMPERORS_CHILDREN_DATASHEETS];
  assert.equal(catalog.length,19);
  assert.deepEqual(catalog.map(d=>d.id),VERIFIED_MUSTER_ENTRIES.map(e=>e.id));
  for (const d of catalog) {
    assert.equal(d.placeholder,false,d.id);
    assert.equal(d.points,VERIFIED_MUSTER_ENTRIES.find(e=>e.id===d.id)!.points);
    assert.ok(d.weapons.length>0,d.id);
    assert.ok(d.abilities.length>0,d.id);
    const u=createUnit(d,d.id,'player-1',Array.from({length:d.modelCount},(_,i)=>({x:i,y:1})));
    assert.equal(u.models.length,d.modelCount);
    assert.ok(u.models.every(m=>m.weaponIds===undefined || m.weaponIds.every(id=>d.weapons.some(w=>w.id===id))));
  }
});
test('Farseer storm rolls D3 damage and both Witchblades critically wound Infantry on 2+', () => {
  const farseer=AELDARI_DATASHEETS.find(d=>d.id==='farseer')!;
  const warlock=AELDARI_DATASHEETS.find(d=>d.id==='warlock')!;
  assert.deepEqual(farseer.weapons.find(w=>w.id==='eldritch-storm')?.damage,{kind:'dice',count:1,sides:3,modifier:0});
  for(const d of [farseer,warlock]) assert.deepEqual(d.weapons.find(w=>w.id==='witchblade')?.weaponAbilities?.find(a=>a.type==='ANTI'),
    {id:'witchblade:anti-infantry',type:'ANTI',keyword:'INFANTRY',threshold:2});
  const s=createTestMatch();
  const bearer=createUnit(farseer,'unit-1','player-1',[{x:4,y:4}]);
  s.definitions=[farseer,s.definitions[1]!];s.units[0]=bearer;
  const target=s.units[1]!, weapon=farseer.weapons.find(w=>w.id==='witchblade')!;
  const job=createAttackJob(weapon,[bearer.models[0]!.id],target,s.definitions[1]!,()=>.17,[],s);
  runAttackJob(job,()=>.17,s);
  assert.equal(job.resolution.attackRecords?.[0]?.criticalWound,true);
  assert.deepEqual(weapon,farseer.weapons.find(w=>w.id==='witchblade'));
});
test('Assured Destruction grants optional rerolls only versus Monster or Vehicle without mutating the datasheet', () => {
  const s=createTestMatch(), dragon=AELDARI_DATASHEETS.find(d=>d.id==='fire-dragons')!;
  s.definitions=[dragon,s.definitions[1]!];
  const unit=createUnit(dragon,'unit-1','player-1',Array.from({length:5},(_,i)=>({x:4+i*1.5,y:5})));
  s.units[0]=unit;
  const base=dragon.weapons.find(w=>w.id==='dragon-fusion-gun')!;
  const infantry=factionAttackWeapon(s,unit,base,s.units[1]!);
  assert.equal(infantry,base);
  s.definitions=s.definitions.map((d,i)=>i===1?{...d,keywords:['VEHICLE']}:d);
  const attack=factionAttackWeapon(s,unit,base,s.units[1]!);
  assert.deepEqual(attack.rerollPermissions?.map(p=>p.kind),['HIT','WOUND','DAMAGE']);
  assert.equal(base.rerollPermissions,undefined);
  const target=s.units[1]!;
  const rolls=[0,.8,.8,.8,.8,.8,.8];let index=0;
  const job=createAttackJob(attack,[unit.models[0]!.id],target,s.definitions[1]!,()=>rolls[index++]??.8,[],s,undefined,{rerolls:{HIT:'FAILED'}});
  runAttackJob(job,()=>rolls[index++]??.8,s);
  assert.equal(job.resolution.attackRecords?.[0]?.hit?.wasRerolled,true);
  assert.equal(job.resolution.attackRecords?.[0]?.hit?.rerollSource,'ASSURED_DESTRUCTION');
});
test('an invalid Assured Destruction target rejects the selected reroll before any attack or state change', async () => {
  const {engine,ok,pass}=await import('./flow.helpers');
  const s=createTestMatch(),dragons=AELDARI_DATASHEETS.find(d=>d.id==='fire-dragons')!;
  s.phase='Shooting';s.definitions=[dragons,s.definitions[1]!];
  s.players[0]!.factionId=dragons.factionId;s.armies[0]!.factionId=dragons.factionId;
  s.units[0]=createUnit(dragons,'unit-1','player-1',Array.from({length:5},(_,i)=>({x:4+i*1.5,y:5})));
  s.units[1]!.models.forEach((m,i)=>m.position={x:4+i*1.5,y:11});
  const e=engine(s);pass(e);
  ok(e.beginShooting('unit-1'));
  ok(e.setAttackChoices('dragon-fusion-gun',{rerolls:{HIT:'FAILED'}}));
  const before=e.getState();let called=false;
  const rejected=e.selectShootingTarget('dragon-fusion-gun','unit-2');
  assert.equal(rejected.ok,false);
  assert.equal(called,false);
  assert.deepEqual(e.getState(),before);
  const target=before.definitions.find(d=>d.id===before.units[1]!.definitionId)!;
  before.definitions=before.definitions.map(d=>d.id===target.id?{...d,keywords:['VEHICLE']}:d);
  const eligible=new GameEngine(before);
  pass(eligible);
  ok(eligible.selectShootingTarget('dragon-fusion-gun','unit-2'));pass(eligible);
  ok(eligible.fireWeapon('dragon-fusion-gun','unit-2',()=>{called=true;return .99;}));
  assert.equal(called,true);
});
test('Rangers use their 5+ invulnerable save against ranged attacks only', () => {
  const s=createTestMatch(),rangers=AELDARI_DATASHEETS.find(d=>d.id==='rangers')!;
  s.definitions=[s.definitions[0]!,rangers];
  const target=createUnit(rangers,'unit-2','player-2',Array.from({length:5},(_,i)=>({x:3+i*1.5,y:12})));
  s.units[1]=target;
  const base=s.definitions[0]!.weapons[0]!;
  const ranged={...base,attacks:{kind:'fixed' as const,value:1},strength:10,armourPenetration:-3};
  const shot=createAttackJob(ranged,[s.units[0]!.models[0]!.id],target,rangers,()=>.75,[],s);
  runAttackJob(shot,()=>.75,s);
  assert.equal(shot.resolution.saveResults[0]?.selected,'INVULNERABLE');
  assert.equal(shot.resolution.saveResults[0]?.saved,true);
  const sword={...ranged,kind:'melee' as const,range:null};
  const strike=createAttackJob(sword,[s.units[0]!.models[0]!.id],target,rangers,()=>.75,[],s);
  runAttackJob(strike,()=>.75,s);
  assert.equal(strike.resolution.saveResults[0]?.selected,'ARMOUR');
  assert.equal(strike.resolution.saveResults[0]?.saved,false);
});
test('Emperor’s Children chosen leader weapons preserve D3 damage and the default Lord loadout', () => {
  const sorcerer=EMPERORS_CHILDREN_DATASHEETS.find(d=>d.id==='sorcerer')!;
  for(const id of ['agonising-energies','force-weapon']) assert.deepEqual(sorcerer.weapons.find(w=>w.id===id)?.damage,
    {kind:'dice',count:1,sides:3,modifier:0});
  const exultant=EMPERORS_CHILDREN_DATASHEETS.find(d=>d.id==='lord-exultant')!;
  assert.deepEqual(exultant.weapons.map(w=>w.id),['bolt-pistol','plasma-pistol','phoenix-power-spear','lord-close-combat-weapon']);
  assert.ok(exultant.keywords.includes('SLAANESH'));
});
test('attached leaders grant Perfectionists and Obsessive Annunciation only while leading', () => {
  const s=createAeldariVsEmperorsChildrenMatch(4);
  const target=s.units.find(u=>u.id==='storm-council')!,infractors=s.units.find(u=>u.id==='infractor-command')!,noise=s.units.find(u=>u.id==='noise-command')!;
  for(const unit of [target,infractors,noise]) unit.location='BATTLEFIELD';
  target.models.forEach((m,i)=>m.position={x:10+i,y:15});
  infractors.models.forEach((m,i)=>m.position={x:10+i,y:13});
  noise.models.forEach((m,i)=>m.position={x:10+i,y:9});
  const weapon=(u:typeof infractors,id:string)=>s.definitions.find(d=>d.id===u.definitionId)!.weapons.find(w=>w.id===id)!;
  const targetDefinition=s.definitions.find(d=>d.id===target.definitionId)!;
  const melee=weapon(infractors,'infractors:duelling-sabre'),infantry=infractors.models.find(m=>m.sourceDefinitionId==='infractors')!;
  const first=createAttackJob(melee,[infantry.id],target,targetDefinition,()=>.99,[],s);
  assert.equal(first.contexts[0]!.abilities.some(a=>a.type==='LETHAL_HITS'&&a.source==='PERFECTIONISTS'),true);
  runAttackJob(first,()=>.99,s);
  assert.equal(first.resolution.attackRecords?.[0]?.automaticallyWoundedFromCriticalHit,true);
  const sonic=weapon(noise,'noise-marines:sonic-blaster'),marine=noise.models.find(m=>m.sourceDefinitionId==='noise-marines')!;
  const second=createAttackJob(sonic,[marine.id],target,targetDefinition,()=>.99,[],s);
  assert.equal(second.contexts[0]!.abilities.some(a=>a.type==='SUSTAINED_HITS'&&a.source==='OBSESSIVE_ANNUNCIATION'),true);
  runAttackJob(second,()=>.99,s);
  assert.equal(second.resolution.attackRecords?.[0]?.generatedAdditionalHits,1);
  const kakophonist=noise.models.find(m=>m.sourceDefinitionId==='lord-kakophonist')!;
  kakophonist.alive=false;kakophonist.woundsRemaining=0;
  const without=createAttackJob(sonic,[marine.id],target,targetDefinition,()=>.99,[],s);
  assert.equal(without.contexts[0]!.abilities.some(a=>a.source==='OBSESSIVE_ANNUNCIATION'),false);
});
test('Guide selects a visible target only at Movement end and improves allied Aeldari Hit rolls until next Command', async () => {
  const {engine,ok,pass}=await import('./flow.helpers');
  const s=createTestMatch(),farseer={...AELDARI_DATASHEETS.find(d=>d.id==='farseer')!,attachment:undefined};
  s.phase='Movement';s.definitions=[farseer,s.definitions[1]!];
  s.players[0]!.factionId=farseer.factionId;s.armies[0]!.factionId=farseer.factionId;
  s.units[0]=createUnit(farseer,'unit-1','player-1',[{x:4,y:4}]);
  s.units[1]!.models.forEach((m,i)=>m.position={x:4+i*1.5,y:10});
  const e=engine(s);pass(e);
  const before=e.getState();assert.equal(e.useGuide('unit-1','unit-2').ok,false);assert.deepEqual(e.getState(),before);
  ok(e.tryNextPhase());
  ok(e.useGuide('unit-1','unit-2'));
  const guided=e.getState();
  assert.equal(guided.flow?.effects.some(x=>x.source==='GUIDE:player-1'&&x.target.unitId==='unit-2'&&x.active),true);
  assert.equal(e.useGuide('unit-1','unit-2').ok,false);
  assert.deepEqual(new GameEngine(guided).getState(),guided);
  const weapon=farseer.weapons.find(w=>w.id==='eldritch-storm')!,unit=guided.units[0]!,target=guided.units[1]!;
  const job=createAttackJob(weapon,[unit.models[0]!.id],target,guided.definitions[1]!,()=>.01,[],guided);
  runAttackJob(job,()=>.2,guided);
  assert.equal(job.resolution.attackRecords?.[0]?.modifiers.some(m=>m.source==='GUIDE'),true);
  assert.equal(job.resolution.attackRecords?.[0]?.hitSucceeded,true);
  guided.turn=3;guided.activePlayerId='player-1';expireEffects(guided,'COMMAND_START');
  assert.equal(guided.flow?.effects.find(x=>x.source==='GUIDE:player-1')?.active,false);
});
test('mixed squads expose independent weapon, wounds, base and objective control',()=>{
  const storm=AELDARI_DATASHEETS.find(d=>d.id==='storm-guardians')!;
  const u=createUnit(storm,'storm','p',Array.from({length:11},(_,i)=>({x:i,y:0})));
  assert.deepEqual(u.models.filter(m=>m.weaponIds?.includes('guardian-fusion-gun')).length,2);
  assert.deepEqual(u.models.at(-1)?.stats?.objectiveControl,0);
  assert.deepEqual(u.models.at(-1)?.base.diameterMm,40);
  assert.equal(u.models.at(-1)?.woundsRemaining,2);
  const dragons=createUnit(AELDARI_DATASHEETS.find(d=>d.id==='fire-dragons')!,'dragons','p',Array.from({length:5},(_,i)=>({x:i,y:0})));
  assert.equal(dragons.models.at(-1)?.woundsRemaining,2);
  assert.equal(dragons.models.filter(m=>m.weaponIds?.includes('exarch-dragon-fusion-gun')).length,1);
});
test('Bladestorm is resolved from the bearer datasheet at half range without editing weapon data',()=>{
  const s=createTestMatch();
  const d=AELDARI_DATASHEETS.find(d=>d.id==='dire-avengers')!;
  const unit=createUnit(d,'unit-1','player-1',Array.from({length:10},(_,i)=>({x:3+i*1.5,y:3})));
  s.definitions=[d,s.definitions[1]!];s.units[0]=unit;
  const target=s.units[1]!;
  target.models.forEach((m,i)=>m.position={x:3+i*1.5,y:9});
  const w=d.weapons.find(w=>w.id==='avenger-shuriken-catapult')!;
  const close=createAttackJob(w,[unit.models[0]!.id],target,s.definitions.find(x=>x.id===target.definitionId)!,()=>.99,[],s);
  assert.equal(close.contexts[0]!.abilities.some(a=>a.source==='BLADESTORM' && a.type==='SUSTAINED_HITS' && a.value===1),true);
  target.models.forEach(m=>m.position={x:m.position.x,y:15});
  const far=createAttackJob(w,[unit.models[0]!.id],target,s.definitions.find(x=>x.id===target.definitionId)!,()=>.99,[],s);
  assert.equal(far.contexts[0]!.abilities.some(a=>a.source==='BLADESTORM'),false);
  assert.equal(w.weaponAbilities?.some(a=>a.type==='SUSTAINED_HITS'),false);
});
test('Guardian Battlehost objective bonus uses original model keywords on an Attached unit',()=>{
  const s=createAeldariVsEmperorsChildrenMatch(42);
  const guardian=s.units.find(u=>u.id==='storm-council')!,enemy=s.units.find(u=>u.id==='noise-command')!;
  guardian.location='BATTLEFIELD';enemy.location='BATTLEFIELD';
  const body=guardian.models.find(m=>m.sourceDefinitionId==='storm-guardians')!,seer=guardian.models.find(m=>m.sourceDefinitionId==='farseer')!;
  body.position={x:6,y:11};seer.position={x:20,y:3};
  enemy.models.forEach((m,i)=>m.position={x:30+i*1.5,y:30});
  const attachedWeapons=s.definitions.find(d=>d.id===guardian.definitionId)!.weapons;
  const weapon=attachedWeapons.find(w=>w.id==='storm-guardians:shuriken-pistol')!;
  const targetDefinition=s.definitions.find(d=>d.id===enemy.definitionId)!;
  const bodyJob=createAttackJob(weapon,[body.id],enemy,targetDefinition,()=>0,[],s);
  runAttackJob(bodyJob,()=>0,s);
  assert.equal(bodyJob.resolution.attackRecords?.[0]?.modifiers.some(m=>m.source==='DEFEND_AT_ALL_COSTS'),true);
  const seerWeapon=attachedWeapons.find(w=>w.id==='farseer:shuriken-pistol')!;
  const seerJob=createAttackJob(seerWeapon,[seer.id],enemy,targetDefinition,()=>0,[],s);
  runAttackJob(seerJob,()=>0,s);
  assert.equal(seerJob.resolution.attackRecords?.[0]?.modifiers.some(m=>m.source==='DEFEND_AT_ALL_COSTS'),false);
});
test('Incursion rosters total 990 and 1000 including enhancement',()=>{
  assert.equal(AELDARI_PRESET.units.length,10);
  assert.equal(EMPERORS_CHILDREN_PRESET.units.length,9);
  assert.equal(AELDARI_PRESET.units.find(u=>u.enhancementId)?.id,'farseer');
});
test('seeded match is stable, detached and ready for deployment with attached passengers',()=>{
  const a=createAeldariVsEmperorsChildrenMatch(42),b=createAeldariVsEmperorsChildrenMatch(42);
  assert.deepEqual(a,b);
  assert.equal(a.deployment?.stage,'DECLARE_BATTLE_FORMATIONS');
  assert.equal(a.mission?.definition.id,'PROVING_GROUND');
  assert.equal(a.units.find(u=>u.id==='infractor-command')?.location,'EMBARKED');
  assert.equal(a.units.find(u=>u.id==='flawless-blades')?.embarked?.transportId,'chaos-land-raider');
  assert.equal(a.attachments?.length,5);
  const engine=GameEngine.create(a);
  const snapshot=engine.getState();snapshot.units[0]!.models[0]!.woundsRemaining=0;
  assert.notEqual(engine.getState().units[0]!.models[0]!.woundsRemaining,0);
  engine.loadMatch(JSON.parse(JSON.stringify(a)));
  assert.deepEqual(engine.getState(),a);
});

test('universal Shock and Assault disembark permissions use transport data', async()=>{
  const { embarked, ok }=await import('./transports.helpers');
  const shock=embarked(),rhino=shock.units.find(u=>u.id==='transport-b')!;
  (shock.definitions.find(d=>d.id===rhino.definitionId)!.transport as {afterAdvance?:string}).afterAdvance='SHOCK';
  rhino.state.hasAdvanced=true;
  const a=new GameEngine(shock);
  assert.equal(ok(a.getDisembarkMode('attached')).mode,'SHOCK');
  ok(a.beginDisembark('attached'));
  assert.equal(a.getState().transportState?.disembark?.mode,'SHOCK');
  const assault=embarked(),raider=assault.units.find(u=>u.id==='transport-b')!;
  (assault.definitions.find(d=>d.id===raider.definitionId)!.transport as {afterNormalMove?:string}).afterNormalMove='ASSAULT';
  raider.lastMove={kind:'NORMAL_MOVE',turn:1,phase:'Movement'};
  const b=new GameEngine(assault);
  assert.equal(ok(b.getDisembarkMode('attached')).mode,'ASSAULT');
  ok(b.beginDisembark('attached'));
  assert.equal(b.getState().transportState?.disembark?.mode,'ASSAULT');
});

test('Aspect Shrine substitutes one paused die without changing weapon or consuming another token',async()=>{
  const { createTestMatch }=await import('../src/game/data/prototype');
  const { engine, ok, pass }=await import('./flow.helpers');
  const s=createTestMatch();s.phase='Shooting';
  const d={...s.definitions[0]!,modelCount:5,abilities:[{id:'ASPECT_SHRINE',name:'Aspect Shrine',parameters:{}}]};
  s.definitions=[d,s.definitions[1]!];
  s.units[0]=createUnit(d,'unit-1','player-1',Array.from({length:5},(_,i)=>({x:4+i*1.5,y:4.5})));
  const e=engine(s);pass(e);
  assert.equal(e.getState().units[0]?.resourceCounters?.ASPECT_SHRINE,1);
  ok(e.beginShooting('unit-1'));ok(e.selectShootingTarget('test-rifle','unit-2'));pass(e);
  const before=e.getState().definitions[0]!.weapons[0]!;
  ok(e.fireWeapon('test-rifle','unit-2',()=>.01));
  assert.equal(e.getState().flow?.window?.trigger,'AFTER_HIT_ROLL');
  ok(e.spendAspectShrineToken());
  assert.equal(e.getState().units[0]?.resourceCounters?.ASPECT_SHRINE,0);
  assert.equal(e.getState().attackJob?.current?.hit?.value,6);
  assert.equal(e.spendAspectShrineToken().ok,false);
  assert.deepEqual(new GameEngine(e.getState()).getState(),e.getState());
  assert.deepEqual(e.getState().definitions[0]!.weapons[0],before);
});

test('Battle Focus Incursion tokens gate movement buff and one manoeuvre per unit per phase', async()=>{
  const { createTestMatch }=await import('../src/game/data/prototype');
  const { engine, ok, pass }=await import('./flow.helpers');
  const s=createTestMatch();s.phase='Movement';
  s.factionRuleIds={'player-1':['BATTLE_FOCUS']};
  s.battleFocus={battleSize:'INCURSION',round:0,tokens:{},usedByPhase:{},manoeuvresByPhase:{}};
  const e=engine(s);pass(e);
  assert.equal(e.getState().battleFocus?.tokens['player-1'],2);
  ok(e.useAgileManoeuvre('SWIFT_AS_THE_WIND','unit-1','MOVE','NORMAL_MOVE'));
  assert.equal(e.getState().battleFocus?.tokens['player-1'],1);
  assert.equal(e.useAgileManoeuvre('FLITTING_SHADOWS','unit-1','MOVE').ok,false);
  ok(e.beginMovement('unit-1'));
  const original=e.getState().units[0]!.models[0]!.position;
  ok(e.moveModel('unit-1:model:1',{x:original.x,y:original.y+8}));
  ok(e.cancelMovement());
  assert.deepEqual(e.getState().units[0]!.models[0]!.position,original);
  assert.equal(e.getState().battleFocus?.tokens['player-1'],1);
  assert.deepEqual(new GameEngine(e.getState()).getState(),e.getState());
});

test('Opportunity Seized reaction rolls D6+1 and moves using the same spatial validators',async()=>{
  const {createTestMatch}=await import('../src/game/data/prototype');
  const {engine,ok,pass}=await import('./flow.helpers');
  const s=createTestMatch();s.turn=2;s.activePlayerId='player-2';s.phase='Movement';
  s.factionRuleIds={'player-1':['BATTLE_FOCUS']};
  s.battleFocus={battleSize:'INCURSION',round:0,tokens:{},usedByPhase:{},manoeuvresByPhase:{}};
  s.units[1]!.models.forEach((m,i)=>m.position={x:4.5+i*1.5,y:6.2});
  const e=engine(s);pass(e);
  ok(e.beginMovement('unit-2','FALL_BACK_MOVE',()=>.99));
  for(const m of e.getState().units[1]!.models) ok(e.moveModel(m.id,{x:m.position.x,y:11}));
  ok(e.completeMovement());
  assert.equal(e.getState().flow?.window?.trigger,'AFTER_ENEMY_FALL_BACK');
  ok(e.useAgileManoeuvre('OPPORTUNITY_SEIZED','unit-1','ENEMY_FALL_BACK',undefined,()=>0));
  assert.equal(e.getState().reactionMove?.allowance,2);
  const before=e.getState();
  assert.equal(e.moveReactionModel('unit-1:model:1',{x:-4,y:4}).ok,false);
  assert.deepEqual(e.getState(),before);
  for(const m of e.getState().units[0]!.models) ok(e.moveReactionModel(m.id,{x:m.position.x,y:m.position.y+2}));
  ok(e.completeReactionMove());
  assert.equal(e.getState().reactionMove,null);
  assert.deepEqual(new GameEngine(e.getState()).getState(),e.getState());
});
