import test from 'node:test';
import assert from 'node:assert/strict';
import { GameEngine } from '../src/game/engine/GameEngine';
import { createUnit } from '../src/game/engine/createUnit';
import { canEmbarkUnit, passengerCost, remainingTransportCapacity } from '../src/game/transports/capacity';
import { validateDisembarkFormation, searchDisembark } from '../src/game/transports/placement';
import { detectDestroyedTransports } from '../src/game/transports/TransportController';
import { baseRadius, edgeDistance } from '../src/game/utils/geometry';
import { ScoutController } from '../src/game/deployment/ScoutController';
import { field, embarked, ok, no } from './transports.helpers';
import type { GameState, Unit } from '../src/game/models';
function addPassenger(s:GameState,id='passenger'):Unit {
 const d=s.definitions.find(d=>d.id==='test-leader')!; const u=createUnit(d,id,'player-1',[{x:17.1,y:15}]);s.units.push(u);s.armies[0]!.unitIds.push(id);return u;
}
for(const kind of ['NORMAL_MOVE','ADVANCE_MOVE','FALL_BACK_MOVE'] as const)test(`legal embark after ${kind} commits parent and removes space`,()=>{
 const s=field(),t=s.units.find(u=>u.id==='transport-b')!;t.models[0]!.position={x:15,y:15};const u=addPassenger(s);
 if(kind==='FALL_BACK_MOVE') {const enemy=s.units.find(u=>u.id==='enemy')!;enemy.models.forEach((m,i)=>m.position={x:19+i*1.5,y:15});}
 const e=new GameEngine(s);ok(e.beginMovement(u.id,kind,()=>.9));if(kind==='FALL_BACK_MOVE')ok(e.moveModel(u.models[0]!.id,{x:17.1,y:13}));ok(e.completeMovement(t.id));
 const after=e.getState().units.find(x=>x.id===u.id)!;assert.equal(after.location,'EMBARKED');assert.equal(after.embarked!.transportId,t.id);new GameEngine(e.getState());
});
test('setup this turn prevents embark without changing transaction',()=>{const s=field(),u=addPassenger(s),t=s.units.find(u=>u.id==='transport-b')!;t.models[0]!.position={x:15,y:15};u.setupAtTurn=1;const e=new GameEngine(s);ok(e.beginMovement(u.id));const before=e.getState();no(e.completeMovement(t.id),'SET_UP_THIS_TURN');assert.deepEqual(e.getState(),before);});
test('capacity exact with weighted model keyword and exclusions',()=>{const s=field(),u=addPassenger(s),t=s.units.find(u=>u.id==='transport-a')!;s.definitions=s.definitions.map(d=>d.id===t.definitionId?{...d,transport:{maximumModels:2,allowedKeywords:['INFANTRY'],excludedKeywords:[],modelCosts:[{keywords:['CHARACTER'],cost:2}]}}:d);assert.equal(passengerCost(s,t,u),2);ok(canEmbarkUnit(s,t,u));s.definitions=s.definitions.map(d=>d.id===t.definitionId?{...d,transport:{...d.transport!,excludedKeywords:['PSYKER']}}:d);no(canEmbarkUnit(s,t,u),'INVALID_PASSENGER');});
test('multiple passengers share remaining capacity',()=>{const s=embarked(),u=addPassenger(s);u.location='EMBARKED';u.embarked={transportId:'transport-b',embarkedAtTurn:1,embarkedAtPhase:'Command',preBattle:true};assert.equal(remainingTransportCapacity(s,s.units.find(u=>u.id==='transport-b')!),4);new GameEngine(s);});
test('Rapid after Ingress inherits enemy setup restrictions',()=>{const s=embarked(),t=s.units.find(u=>u.id==='transport-b')!;t.arrival={method:'DEEP_STRIKE',ingressMethod:'DEEP_STRIKE',turn:1};const e=new GameEngine(s);assert.equal(ok(e.getDisembarkMode('attached')).mode,'RAPID');ok(e.beginDisembark('attached'));assert.equal(e.getState().transportState!.disembark!.setupConstraints.enemyDistance,8);new GameEngine(e.getState());});
test('Rapid validates wholly within three and charge restriction after commit',()=>{const s=embarked(),u=s.units.find(u=>u.id==='attached')!,t=s.units.find(u=>u.id==='transport-b')!;const placement=searchDisembark(s,u,t.models[0]!,3,{});assert.ok(placement.formation);t.state.hasMoved=true;const e=new GameEngine(s);ok(e.beginDisembark(u.id));for(const [id,p]of Object.entries(placement.formation!))ok(e.stageDisembarkModel(id,p));ok(e.completeDisembark());assert.equal(e.getState().units.find(x=>x.id===u.id)!.cannotChargeUntilTurn,1);new GameEngine(e.getState());});
test('wholly-within differs from nearest edge for disembark',()=>{const s=embarked(),u=addPassenger(s),t=s.units.find(u=>u.id==='transport-b')!.models[0]!;u.location='EMBARKED';const p={x:t.position.x+baseRadius(t.base)+3,y:t.position.y};no(validateDisembarkFormation(s,u,t,{[u.models[0]!.id]:p},3,{}),'TOO_FAR_FROM_TRANSPORT');});
test('Combat fallback rolls Hazard, shocks and prohibits Charge',()=>{
 const s=embarked(),t=s.units.find(u=>u.id==='transport-b')!,u=addPassenger(s);s.units.find(x=>x.id==='attached')!.location='RESERVES';delete s.units.find(x=>x.id==='attached')!.embarked;
 u.location='EMBARKED';u.embarked={transportId:t.id,embarkedAtTurn:1,embarkedAtPhase:'Command',preBattle:true};
 const enemy=s.units.find(x=>x.id==='enemy')!;enemy.models.push({...enemy.models[0]!,id:'enemy:model:6'});s.definitions=s.definitions.map(d=>d.id===enemy.definitionId?{...d,modelCount:6}:d);enemy.models.forEach((m,i)=>{const a=i*Math.PI*2/6;m.position={x:15+Math.cos(a)*3,y:15+Math.sin(a)*3};});
 const e=new GameEngine(s);assert.equal(ok(e.getDisembarkMode(u.id)).mode,'COMBAT');ok(e.beginDisembark(u.id,()=>.9));assert.deepEqual(e.getState().transportState!.disembark!.hazard!.rolls,[6]);
 const placement=searchDisembark(e.getState(),u,t.models[0]!,6,{},[enemy.id]);assert.ok(placement.formation);for(const[id,p]of Object.entries(placement.formation!))ok(e.stageDisembarkModel(id,p));ok(e.completeDisembark());const after=e.getState().units.find(x=>x.id===u.id)!;assert.equal(after.state.battleShocked,true);assert.equal(after.cannotChargeUntilTurn,1);
});
test('Emergency resolves multiple manifests in sequence and keeps frozen parent until last',()=>{const s=embarked(),u=addPassenger(s),t=s.units.find(x=>x.id==='transport-b')!;u.location='EMBARKED';u.embarked={transportId:t.id,embarkedAtTurn:1,embarkedAtPhase:'Command',preBattle:true};t.models[0]!.alive=false;t.models[0]!.woundsRemaining=0;detectDestroyedTransports(s);const e=new GameEngine(s);ok(e.beginDisembark('attached',()=>.9));ok(e.resolveEmergencyDisembark());assert.equal(e.getState().transportState!.destroyed.length,1);new GameEngine(e.getState());ok(e.beginDisembark(u.id,()=>.9));ok(e.resolveEmergencyDisembark());assert.equal(e.getState().transportState!.destroyed.length,0);new GameEngine(e.getState());});
test('Emergency chooses nearest base tangencies and all survivors remain within six',()=>{const s=embarked(),t=s.units.find(x=>x.id==='transport-b')!;t.models[0]!.alive=false;t.models[0]!.woundsRemaining=0;detectDestroyedTransports(s);const e=new GameEngine(s);ok(e.beginDisembark('attached',()=>.9));ok(e.resolveEmergencyDisembark());const u=e.getState().units.find(x=>x.id==='attached')!;assert.ok(edgeDistance(u.models[0]!,t.models[0]!)<1e-5);assert.ok(u.models.filter(m=>m.alive).every(m=>edgeDistance(m,t.models[0]!)<6));});
test('placement search exhaustion is explicit and never treated as impossible',()=>{const s=embarked(),u=s.units.find(x=>x.id==='attached')!,t=s.units.find(x=>x.id==='transport-b')!;assert.equal(searchDisembark(s,u,t.models[0]!,3,{},[],0).exhausted,true);});
for(const trait of ['ONE_SHOT','ONE SHOT'])test(`Firing Deck rejects ${trait}`,()=>{const s=embarked();s.definitions=s.definitions.map(d=>({...d,weapons:d.weapons.map(w=>({...w,traits:[{id:trait}]}))}));s.phase='Shooting';assert.deepEqual(new GameEngine(s).getFiringDeckOptions('transport-b'),[]);});
test('already selected passengers cannot supply Firing Deck',()=>{const s=embarked();s.phase='Shooting';s.units.find(u=>u.id==='attached')!.selectedToShootAt={turn:1,phase:'Shooting'};assert.deepEqual(new GameEngine(s).getFiringDeckOptions('transport-b'),[]);});
test('Firing Deck weapon fires through shared Shooting and disappears after completion',()=>{const s=embarked();s.phase='Shooting';const e=new GameEngine(s),selected=e.getFiringDeckOptions('transport-b').slice(0,1),catalog=e.getState().definitions;ok(e.beginShooting('transport-b',selected));const weapon=e.getState().shooting!.firingDeck![0]!.borrowed;ok(e.fireWeapon(weapon.id,'enemy',()=>0));new GameEngine(e.getState());ok(e.completeShooting());assert.deepEqual(e.getState().definitions,catalog);assert.equal(e.getState().shooting,null);new GameEngine(e.getState());});
test('Advance consumes explicit RNG, extra allowance survives snapshot and cannot cancel',()=>{const s=field(),u=addPassenger(s);const e=new GameEngine(s);ok(e.beginMovement(u.id,'ADVANCE_MOVE',()=>.9));no(e.cancelMovement(),'IRREVERSIBLE_ACTION');ok(e.moveModel(u.models[0]!.id,{x:29.1,y:15}));new GameEngine(e.getState());ok(e.completeMovement());new GameEngine(e.getState());});
test('Emergency destroys a model whose base cannot fit wholly within six without overlapping parent',()=>{const s=embarked(),attached=s.units.find(u=>u.id==='attached')!,u=addPassenger(s),t=s.units.find(u=>u.id==='transport-b')!;attached.location='RESERVES';delete attached.embarked;u.models[0]!.base={kind:'circle',diameterMm:203.2};u.location='EMBARKED';u.embarked={transportId:t.id,embarkedAtTurn:1,embarkedAtPhase:'Command',preBattle:true};t.models[0]!.alive=false;t.models[0]!.woundsRemaining=0;detectDestroyedTransports(s);const e=new GameEngine(s);ok(e.beginDisembark(u.id,()=>.9));ok(e.resolveEmergencyDisembark());assert.equal(e.getState().units.find(x=>x.id===u.id)!.location,'DESTROYED');assert.ok(e.getState().events.some(x=>x.type==='flow'&&x.name==='TRANSPORT_PASSENGER_DESTROYED'));new GameEngine(e.getState());});
test('all Hazard casualties finish emergency without orphan passenger state',()=>{const s=embarked(),attached=s.units.find(u=>u.id==='attached')!,u=addPassenger(s),t=s.units.find(u=>u.id==='transport-b')!;attached.location='RESERVES';delete attached.embarked;u.models[0]!.woundsRemaining=1;u.location='EMBARKED';u.embarked={transportId:t.id,embarkedAtTurn:1,embarkedAtPhase:'Command',preBattle:true};t.models[0]!.alive=false;t.models[0]!.woundsRemaining=0;detectDestroyedTransports(s);const e=new GameEngine(s);ok(e.beginDisembark(u.id,()=>0));new GameEngine(e.getState());ok(e.resolveEmergencyDisembark());new GameEngine(e.getState());assert.equal(e.getState().units.find(x=>x.id===u.id)!.embarked,undefined);});
test('dedicated inherited Scouts uses the existing ScoutMoveTransaction',()=>{const s=embarked();s.phase='Command';s.deployment={stage:'PRE_BATTLE_RULES',zones:[{id:'a',playerId:'player-1',footprint:{vertices:[{x:0,y:0},{x:48,y:0},{x:48,y:18},{x:0,y:18}]},metadata:{}},{id:'b',playerId:'player-2',footprint:{vertices:[{x:0,y:28},{x:48,y:28},{x:48,y:36},{x:0,y:36}]},metadata:{}}],pointsLimit:1000,rules:{strategicReservePointsLimitRatio:.5,standardIngressMinimumRound:2,ingressEdgeDistance:6,enemySetupDistance:8,infiltratorZoneDistance:8,scoutEnemyDistance:8,enemyZoneAllowedRound:3,reserveExpirationRound:3},firstDeploymentPlayerId:'player-1',nextPlayerId:'player-1',firstTurnPlayerId:'player-1',deployed:s.units.filter(u=>u.location==='BATTLEFIELD').map(u=>u.id),scoutDone:[],choices:{},initialReserveIds:[]};const e=new GameEngine(s);ok(e.beginScoutMove('transport-b'));assert.equal(e.getState().scout!.kind,'SCOUT_MOVE');assert.equal(e.getState().scout!.allowance,6);new GameEngine(e.getState());ok(e.cancelScoutMove());});
test('supplied continuous Tactical formation bypasses candidate search but is fully validated',()=>{const s=embarked(),u=s.units.find(u=>u.id==='attached')!,t=s.units.find(u=>u.id==='transport-b')!;const f=searchDisembark(s,u,t.models[0]!,3,{}).formation!;const e=new GameEngine(s);ok(e.beginDisembark(u.id,undefined,f));ok(e.completeDisembark());assert.equal(e.getState().transportState!.tacticalFollowUp,u.id);});
test('failed placement search never declares a terrain-based impossibility',()=>{const s=embarked(),u=s.units.find(u=>u.id==='attached')!,t=s.units.find(u=>u.id==='transport-b')!;s.battlefield.terrain={areas:[],features:[]};const result=searchDisembark(s,u,t.models[0]!,3,{},[],0);assert.equal(result.exhausted,true);assert.equal(result.formation,null);});
test('transport queries leave complete snapshot unchanged',()=>{const e=new GameEngine(embarked()),before=e.getState();e.getTransportDebug();e.getFiringDeckOptions('transport-b');e.getDisembarkMode('attached');assert.deepEqual(e.getState(),before);});
test('Firing Deck may select zero passenger weapons and still round-trip safely',()=>{const s=embarked();s.phase='Shooting';const e=new GameEngine(s);ok(e.beginShooting('transport-b',[]));new GameEngine(e.getState());ok(e.completeShooting());new GameEngine(e.getState());});
